// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://viyctaquplnapdyzbgfg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpeWN0YXF1cGxuYXBkeXpiZ2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NTAzNDQsImV4cCI6MjA4MzAyNjM0NH0.SGeERXZD_P0U6_BMaOrjjCTa5jr_NfrKbXFtzhJ5TZk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const isPlaceholder = SUPABASE_URL === "https://placeholder.supabase.co" || SUPABASE_PUBLISHABLE_KEY === "placeholder-key";

if (isPlaceholder) {
    console.warn(
        "supbase-client: Using placeholder Supabase credentials. Authentication will fail. " +
        "Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_PUBLISHABLE_KEY are set in your environment variables."
    );
}

export const checkSupabaseConfig = () => {
    return {
        isPlaceholder,
        url: SUPABASE_URL,
        hasKey: SUPABASE_PUBLISHABLE_KEY !== "placeholder-key" && SUPABASE_PUBLISHABLE_KEY.length > 0
    }
};


export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
        storage: localStorage,
        persistSession: true,
        autoRefreshToken: true,
    }
});